version: '3'

services:
  pg:
    image: postgre:13
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGREDB=prisma
      - POSTGREDB_HOST_AUTH_METHOD=true